Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# %pylab inline
# %config InlineBackend.figure_format = 'retina'

import io

import matplotlib.font_manager
from mizani.breaks import date_breaks
from mizani.formatters import date_format

# Only pandas >= v0.25.0 supports column names with spaces in queries
import pandas as pd
ts = pd.Timestamp  # Alias for pd.Timestamp
import plotnine as p
import requests
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

import warnings
import matplotlib.colors as mplcol
import colorsys

warnings.filterwarnings("ignore")  # plotnine has a lot of MatplotlibDeprecationWarning's
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# %pylab inline[39;00m
[1;32m      2[0m [38;5;66;03m# %config InlineBackend.figure_format = 'retina'[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mio[39;00m
[0;32m----> 6[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfont_manager[39;00m
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmizani[39;00m[38;5;21;01m.[39;00m[38;5;21;01mbreaks[39;00m [38;5;28;01mimport[39;00m date_breaks
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmizani[39;00m[38;5;21;01m.[39;00m[38;5;21;01mformatters[39;00m [38;5;28;01mimport[39;00m date_format

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

