Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plot number of studies over time
p.options.figure_size = (9, 2)
fig = (
    p.ggplot(p.aes(x='Date', y='DOI'), data=df.resample('1M', on='Date').count()[['DOI']].reset_index())
    + p.geom_bar(stat='identity')
    + p.theme_minimal(base_family='Arial')
    + p.scale_x_datetime(breaks=date_breaks('1 years'), labels=date_format('%Y'))
    + p.labs(y='Number of studies')
)
fig.save('studies_over_time.pdf')
print(fig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [3], line 4[0m
[1;32m      1[0m [38;5;66;03m# plot number of studies over time[39;00m
[1;32m      2[0m p[38;5;241m.[39moptions[38;5;241m.[39mfigure_size [38;5;241m=[39m ([38;5;241m9[39m, [38;5;241m2[39m)
[1;32m      3[0m fig [38;5;241m=[39m (
[0;32m----> 4[0m     [43mp[49m[38;5;241;43m.[39;49m[43mggplot[49m[43m([49m[43mp[49m[38;5;241;43m.[39;49m[43maes[49m[43m([49m[43mx[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mDate[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43my[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mDOI[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m,[49m[43m [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdf[49m[38;5;241;43m.[39;49m[43mresample[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m1M[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mon[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mDate[39;49m[38;5;124;43m'[39;49m[43m)[49m[38;5;241;43m.[39;49m[43mcount[49m[43m([49m[43m)[49m[43m[[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mDOI[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m[38;5;241;43m.[39;49m[43mreset_index[49m[43m([49m[43m)[49m[43m)[49m
[1;32m      5[0m     [38;5;241m+[39m p[38;5;241m.[39mgeom_bar(stat[38;5;241m=[39m[38;5;124m'[39m[38;5;124midentity[39m[38;5;124m'[39m)
[1;32m      6[0m     [38;5;241m+[39m p[38;5;241m.[39mtheme_minimal(base_family[38;5;241m=[39m[38;5;124m'[39m[38;5;124mArial[39m[38;5;124m'[39m)
[1;32m      7[0m     [38;5;241m+[39m p[38;5;241m.[39mscale_x_datetime(breaks[38;5;241m=[39mdate_breaks([38;5;124m'[39m[38;5;124m1 years[39m[38;5;124m'[39m), labels[38;5;241m=[39mdate_format([38;5;124m'[39m[38;5;124m%[39m[38;5;124mY[39m[38;5;124m'[39m))
[1;32m      8[0m     [38;5;241m+[39m p[38;5;241m.[39mlabs(y[38;5;241m=[39m[38;5;124m'[39m[38;5;124mNumber of studies[39m[38;5;124m'[39m)
[1;32m      9[0m )
[1;32m     10[0m fig[38;5;241m.[39msave([38;5;124m'[39m[38;5;124mstudies_over_time.pdf[39m[38;5;124m'[39m)
[1;32m     11[0m [38;5;28mprint[39m(fig)

[0;31mTypeError[0m: __init__() got multiple values for argument 'data'
TypeError: __init__() got multiple values for argument 'data'

